### ISSUE TITLE
Consider using Redux Starter Kit?

### ISSUE THREAD

**Issue by markerikson** [productioncoder/youtube-react#1]
Hi, I'm a Redux maintainer.

I saw a link to your project today, and it looks pretty neat.  

We have a new [Redux Starter Kit package](https://redux-starter-kit.js.org) can simplify a lot of common Redux usage patterns, including store setup, defining reducers, immutable update logic, and even creating entire "slices" of state automatically without writing any action creators or action types by hand.

I'm hoping to add a "Usage Guide" docs page in the near future, and I've [actually been looking for a moderately complex app](https://twitter.com/acemarke/status/1085052200680939526) that I can use as a basis for demonstrating the ways that Redux Starter Kit can simplify things.  Youtube-React looks like the reducer logic and store setup fit that "medium complexity" level I'm looking for, although the use of sagas is not something I care about right now.

So, two thoughts:

- First, wanted to let you know that I might be using some of the code as a starting point for some of the examples / tutorials I hope to write in the near future.
- Second, I would _love_ to have you convert some of Youtube-React's actual code to use Redux Starter Kit and show how to use it in your videos!

If you've got any questions or anything I can help with, please ping me [@acemarke on Twitter](https://twitter.com/acemarke) and Reactiflux, or tag me here on Github.

**Comment by productioncoder** [comment]
Hi @markerikson ,

sry. for the delay.

> First, wanted to let you know that I might be using some of the code as a starting point for some of the examples / tutorials I hope to write in the near future

Great, looking forward to it 👍. Feel free to use any parts of the code as needed. There is also a written [tutorial series that explains the project](https://productioncoder.com/build-youtube-in-react-part-1/). The Redux part will start roughly from part 20 onwards which is not yet released.

> Second, I would love to have you convert some of Youtube-React's actual code to use Redux Starter Kit and show how to use it in your videos!

We can definitely think about doing so. However, I already finished with all the 45 written tutorials. Therefore I'd rather release all of them first and then we could about restructuring it. Otherwise I have to rewrite about 25 tutorials (with 1000+ words each).

**Comment by markerikson** [comment]
Sure, I figured something like that might be the case.  Just wanted to bring Redux Starter Kit to your attention.  Hope it helps!
